# This is a basic workflow to help you get started with Actions

name: Compatibility Tests

# Controls when the workflow will run
on:
  # Trigger actions on all branches
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ubuntu20:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install fio, python2 and pip
        run: |
          sudo apt-get install -y fio python3 python3-pip
      - name: Test python3
        run: |
          pip install .
          cdm -s 1m
  windows2022:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Test python3
        run: |
          pip install .
          cdm -s 1m
